modLoader="javafml"

issueTrackerURL="https://github.com/Matyrobbrt/SpookyAutumn/issues"

[[mods]]

modId="spookyautumn"

version="${file.jarVersion}" 

displayName="Spooky Autumn"

displayURL="https://github.com/Matyrobbrt/SpookyAutumn"

#logoFile="examplemod.png" #optional

#credits="Thanks for this example mod goes to Java" #optional

authors="The Refinement Dev Team"

description='''

'''

[[dependencies.spookyautumn]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.spookyautumn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
